config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get    '/books'           , to: 'books#index'  , as: :book_index
  post   '/books'           , to: 'books#create' 
  get    '/books/new'       , to: 'books#new'    , as: :new_book
  get    '/books/:id/edit'  , to: 'books#edit'   , as: :edit_book
  
  get    '/books/:id'       , to: 'books#show'   , as: :book
  patch  '/books/:id'       , to: 'books#update' 
  delete '/books/:id'       , to: 'books#delete'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

    before_action :find_book, only: [:show, :edit, :update, :delete]

    def index
    end

    def new
        @book = Book.new
    end

    def show
    end

    def create
        @book = Book.new(params_book)

        if @book.save 
            redirect_to books_path, notice: "book created"
        else
            redirect_to new
        end
    end

    def edit 
    end

    def update 
        if @book.update_attributes(params_book)
            redirect_to books_path, notice: "book saved"
        else
            render edit
        end
    end

    def delete
        @book.delete
        redirect_to book_index_path
    end


    private

    def params_book
        params.require(:book).permit(:name,:author)
    end

    def find_book
        @book = Book.find(params[:id])
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for @book do |f| %>

    <div class="row">

        <div class="col-md-3">
            <%=f.label :name %>
        </div>
        <div class="col-md-9">
            <%=f.text_field :name %>
        </div>
        <div class="col-md-3">
            <%=f.label :author %>
        </div>
        <div class="col-md-9">
            <%=f.text_field :author %>
        </div>

        <div class="col-md-12">
            <%=f.submit%>
        </div>
    </div>
<% end %>

app/views/books/edit.html.erb
<%= render 'form' %>

<%= link_to "back", books_path %>

app/views/books/index.html.erb
<div class="row">
    <div class="col-md-2">&nbsp;</div>
    <div class="col-md-5">
        Name
    </div>
    <div class="col-md-5">
        Author
    </div>
</div>

<% Book.all.each do |bk| %>

    <div class="row">
        <div class="col-md-2">
            [<%= link_to  "e", edit_book_path(bk) %>]
            [<%= link_to  "d", book_path(bk), method: :delete %>]
        </div>
        <div class="col-md-5">
            <%=bk.name%>
        </div>
        <div class="col-md-5">
            <%=bk.author%>
        </div>
    </div>
    
<% end %>

<%= link_to  "New", new_book_path %>

app/views/books/new.html.erb
<%= render 'form' %>

<%= link_to "back", books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookshelf </title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body class="bgmain">
    
    <div class="container">

      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <%= yield %>
        </div> 
        <div class="col-md-2"></div>
      </div>

    </div>

  </body>
</html>